branches:
  - master
  - /^v\d+\.\d+(?:\.\d+)?(?:-\S*)?$/
cache: bundler
language: ruby
rvm:
  - 2.5.1
script: bundle exec rake
sudo: false

before_install:
  - gem update --system --no-doc --no-ri
  - gem install bundler -v '1.17.3'

after_script:
  - bundle exec codeclimate-test-reporter

bundler_args: --without development --with ci
